let
    Source = Excel.Workbook(Web.Contents("https://[REDACTED].sharepoint.com/sites/PowerBIDashboards/Shared%20Documents/General/PowerBI%20Clients/[REDACTED]/DO%20NOT%20MOVE/Cash%20Flow.xlsx"), null, true),
    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Column1", "Account"}}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Renamed Columns", {"Account"}, "Attribute", "Value"),
    #"Renamed Columns1" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "Date"}, {"Value", "Amount"}}),
    #"Filtered Rows1" = Table.SelectRows(#"Renamed Columns1", each ([Date] <> "Total")),
    #"Trimmed Text" = Table.TransformColumns(#"Filtered Rows1",{{"Account", Text.Trim, type text}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Trimmed Text",{{"Date", type date}, {"Amount", type number}}),
    #"Replaced Value" = Table.ReplaceValue(#"Changed Type2","Net Income","30000 Net Income",Replacer.ReplaceText,{"Account"}),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Replaced Value", "Text Before Delimiter", each Text.BeforeDelimiter([Account], " "), type text),
    #"Renamed Columns2" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "Account #"}}),
    #"Filtered Rows" = Table.SelectRows(#"Renamed Columns2", each ([Account] <> "Net cash provided by financing activities" and [Account] <> "Net cash provided by investing activities" and [Account] <> "Total Adjustments to reconcile 30000 Net Income to Net Cash provided by operations:")),
    #"Added Account # 2" = Table.AddColumn(#"Filtered Rows", "Account # 2",
    each 
        if [Account] = "Account Name 1" then 1000001 
        else if [Account] = "Account Name 2" then 1000002 
        else if [Account] = "Account Name 3" then 1000003 
        else if [Account] = "Account Name 4" then 1000004 
        else if [Account] = "Account Name 5" then 1000005 
        else if [Account] = "Account Name 6" then 1000006
        else if [#"Account #"] = "1071*" then 1000007
        else if [#"Account #"] = "1072*" then 1000008
        else if [#"Account #"] = "90000" then 1000009
        else if [Account] = "Account Name 7" then 1000010
        else if [Account] = "Account Name 8" then 2000001 
        else if [Account] = "Account Name 9" then 2000002 
        else if [Account] = "Account Name 10" then 2000003 
        else if [Account] = "Account Name 11" then 2000004 
        else if [Account] = "Account Name 12" then 2000005
        else if [Account] = "Account Name 13" then 2000006 
        else if [Account] = "Account Name 14" then 2000007 
        else if [Account] = "Account Name 15" then 2000008 
        else if [Account] = "Account Name 16" then 2000009 
        else if [Account] = "Account Name 17" then 2000010 
        else if [Account] = "Account Name 18" then 2000011 
        else if [Account] = "Account Name 19" then 2000012 
        else if [Account] = "Account Name 20" then 2000013 
        else if [Account] = "Account Name 21" then 2000014
        else if [Account] = "Account Name 22" then 2000015    
        else if [Account] = "Billable Expense Income" then 4000001 
        else if [Account] = "Markup" then 4000002 
        else if [Account] = "Revenue***" then 4000003 
        else if [Account] = "Sales" then 4000004 
        else if [Account] = "Sales of Product Income" then 4000005 
        else if [Account] = "Shipping Income" then 4000006 
        else if [Account] = "Unapplied Cash Payment Income" then 4000007
        else if [Account] = "Cost of Goods Sold" then 5000001 
        else if [Account] = "Purchases" then 6000001 
        else if [Account] = "Unapplied Cash Bill Payment Expense" then 6000002 
        else if [Account] = "Uncategorized Expense" then 6000003 
        else if [Account] = "Uncategorized Expense ( 623 )" then 6000004
        else if [#"Account #"] = "57000" then 6000005
        else if [#"Account #"] = "57100" then 6000006
        else if [#"Account #"] = "57110" then 6000007
        else if [#"Account #"] = "57120" then 6000008
        else if [#"Account #"] = "57130" then 6000009
        else if [#"Account #"] = "57200" then 6000010
        else if [#"Account #"] = "57210" then 6000011
        else if [#"Account #"] = "57220" then 6000012
        else if [#"Account #"] = "57230" then 6000013
        else if [#"Account #"] = "57240" then 6000014
        else if [#"Account #"] = "57250" then 6000015
        else if [#"Account #"] = "57260" then 6000016
        else if [#"Account #"] = "57270" then 6000017
        else if [#"Account #"] = "57300" then 6000018
        else if [#"Account #"] = "57310" then 6000019
        else if [#"Account #"] = "57320" then 6000020
        else if [#"Account #"] = "57330" then 6000021
        else if [#"Account #"] = "57340" then 6000022
        else if [#"Account #"] = "57350" then 6000023
        else if [#"Account #"] = "57360" then 6000024
        else if [#"Account #"] = "57370" then 6000025
        else if [#"Account #"] = "57380" then 6000026
        else if [#"Account #"] = "57400" then 6000027
        else if [#"Account #"] = "57415" then 6000028
        else if [#"Account #"] = "57420" then 6000029
        else if [#"Account #"] = "57430" then 6000030
        else if [#"Account #"] = "57440" then 6000031
        else if [#"Account #"] = "57450" then 6000032
        else if [#"Account #"] = "57460" then 6000033
        else if [#"Account #"] = "57500" then 6000034
        else if [#"Account #"] = "57510" then 6000035
        else if [#"Account #"] = "57520" then 6000036
        else if [#"Account #"] = "57530" then 6000037
        else if [#"Account #"] = "57540" then 6000038
        else if [#"Account #"] = "57550" then 6000039
        else if [#"Account #"] = "57570" then 6000040
        else if [#"Account #"] = "57580" then 6000041
        else if [#"Account #"] = "57600" then 6000042
        else if [#"Account #"] = "57800" then 6000043
        else if [Account] = "Employee Retention Credit" then 7000001  
        else if [#"Account #"] = "70200" then 8000001 
        else if [#"Account #"] = "70300" then 8000002 
        else if [#"Account #"] = "70350" then 8000003 
        else if [#"Account #"] = "70400" then 8000004 
        else if [#"Account #"] = "70500" then 8000005
        else if [#"Account #"] = "70550" then 8000006 
        else if [Account] = "Reconciliation Discrepancies-1" then 8000007 
        else [#"Account #"]
),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Account # 2",{{"Account # 2", type text}}),
    #"Removed Columns1" = Table.RemoveColumns(#"Changed Type3",{"Account #"}),
    #"Renamed Columns3" = Table.RenameColumns(#"Removed Columns1",{{"Account # 2", "Account #"}}),
    #"Filtered Rows2" = Table.SelectRows(#"Renamed Columns3", each ([Account] <> "Net cash provided by operating activities"))
in
    #"Filtered Rows2"