let
    Source = Excel.Workbook(Web.Contents("https://[REDACTED].sharepoint.com/sites/PowerBIDashboards/Shared%20Documents/General/PowerBI%20Clients/[REDACTED]/DO%20NOT%20MOVE/WEC%20Transaction%20Detail.xlsx"), null, true),
    #"Transaction Detail by  Account " = Source{[Item="Transaction Detail by Account",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(#"Transaction Detail by  Account ", [PromoteAllScalars=true]),
    #"Renamed Columns" = Table.RenameColumns(#"Promoted Headers",{{"Class", "Location"}}),
    #"Removed Other Columns1" = Table.SelectColumns(#"Renamed Columns",{"Date", "Account", "Location", "Amount"}),
    #"Changed Type" = Table.TransformColumnTypes(#"Removed Other Columns1",{{"Date", type date}, {"Account", type text}, {"Location", type text}, {"Amount", type number}}),
    #"Filtered Rows1" = Table.SelectRows(#"Changed Type", each ([Date] <> null) and ([Account] <> null)),
    #"Inserted Text Before Delimiter" = Table.AddColumn(#"Filtered Rows1", "Text Before Delimiter", each Text.BeforeDelimiter([Account], " "), type text),
    #"Renamed Columns1" = Table.RenameColumns(#"Inserted Text Before Delimiter",{{"Text Before Delimiter", "Account #"}}),
    #"Added Account # 2" = Table.AddColumn(#"Renamed Columns1", "Account # 2",
    each 
        if [Account] = "Account Name 1" then 1000001 
        else if [Account] = "Account Name 2" then 1000002 
        else if [Account] = "Account Name 3" then 1000003 
        else if [Account] = "Account Name 4" then 1000004 
        else if [Account] = "Account Name 5" then 1000005 
        else if [Account] = "Account Name 6" then 1000006
        else if [#"Account #"] = "1071*" then 1000007
        else if [#"Account #"] = "1072*" then 1000008
        else if [#"Account #"] = "90000" then 1000009
        else if [Account] = "Account Name 7" then 1000010
        else if [Account] = "Account Name 8" then 2000001 
        else if [Account] = "Account Name 9" then 2000002 
        else if [Account] = "Account Name 10" then 2000003 
        else if [Account] = "Account Name 11" then 2000004 
        else if [Account] = "Account Name 12" then 2000005
        else if [Account] = "Account Name 13" then 2000006 
        else if [Account] = "Account Name 14" then 2000007 
        else if [Account] = "Account Name 15" then 2000008 
        else if [Account] = "Account Name 16" then 2000009 
        else if [Account] = "Account Name 17" then 2000010 
        else if [Account] = "Account Name 18" then 2000011 
        else if [Account] = "Account Name 19" then 2000012 
        else if [Account] = "Account Name 20" then 2000013 
        else if [Account] = "Account Name 21" then 2000014
        else if [Account] = "Account Name 22" then 2000015    
        else if [Account] = "Billable Expense Income" then 4000001 
        else if [Account] = "Markup" then 4000002 
        else if [Account] = "Revenue***" then 4000003 
        else if [Account] = "Sales" then 4000004 
        else if [Account] = "Sales of Product Income" then 4000005 
        else if [Account] = "Shipping Income" then 4000006 
        else if [Account] = "Unapplied Cash Payment Income" then 4000007
        else if [Account] = "Cost of Goods Sold" then 5000001 
        else if [Account] = "Purchases" then 6000001 
        else if [Account] = "Unapplied Cash Bill Payment Expense" then 6000002 
        else if [Account] = "Uncategorized Expense" then 6000003 
        else if [Account] = "Uncategorized Expense ( 623 )" then 6000004
        else if [#"Account #"] = "57000" then 6000005
        else if [#"Account #"] = "57100" then 6000006
        else if [#"Account #"] = "57110" then 6000007
        else if [#"Account #"] = "57120" then 6000008
        else if [#"Account #"] = "57130" then 6000009
        else if [#"Account #"] = "57200" then 6000010
        else if [#"Account #"] = "57210" then 6000011
        else if [#"Account #"] = "57220" then 6000012
        else if [#"Account #"] = "57230" then 6000013
        else if [#"Account #"] = "57240" then 6000014
        else if [#"Account #"] = "57250" then 6000015
        else if [#"Account #"] = "57260" then 6000016
        else if [#"Account #"] = "57270" then 6000017
        else if [#"Account #"] = "57300" then 6000018
        else if [#"Account #"] = "57310" then 6000019
        else if [#"Account #"] = "57320" then 6000020
        else if [#"Account #"] = "57330" then 6000021
        else if [#"Account #"] = "57340" then 6000022
        else if [#"Account #"] = "57350" then 6000023
        else if [#"Account #"] = "57360" then 6000024
        else if [#"Account #"] = "57370" then 6000025
        else if [#"Account #"] = "57380" then 6000026
        else if [#"Account #"] = "57400" then 6000027
        else if [#"Account #"] = "57415" then 6000028
        else if [#"Account #"] = "57420" then 6000029
        else if [#"Account #"] = "57430" then 6000030
        else if [#"Account #"] = "57440" then 6000031
        else if [#"Account #"] = "57450" then 6000032
        else if [#"Account #"] = "57460" then 6000033
        else if [#"Account #"] = "57500" then 6000034
        else if [#"Account #"] = "57510" then 6000035
        else if [#"Account #"] = "57520" then 6000036
        else if [#"Account #"] = "57530" then 6000037
        else if [#"Account #"] = "57540" then 6000038
        else if [#"Account #"] = "57550" then 6000039
        else if [#"Account #"] = "57570" then 6000040
        else if [#"Account #"] = "57580" then 6000041
        else if [#"Account #"] = "57600" then 6000042
        else if [#"Account #"] = "57800" then 6000043
        else if [Account] = "Employee Retention Credit" then 7000001  
        else if [#"Account #"] = "70200" then 8000001 
        else if [#"Account #"] = "70300" then 8000002 
        else if [#"Account #"] = "70350" then 8000003 
        else if [#"Account #"] = "70400" then 8000004 
        else if [#"Account #"] = "70500" then 8000005
        else if [#"Account #"] = "70550" then 8000006 
        else if [Account] = "Reconciliation Discrepancies-1" then 8000007 
        else [#"Account #"]
),
    #"Changed Type2" = Table.TransformColumnTypes(#"Added Account # 2",{{"Account # 2", type text}}),
    #"Merged Queries" = Table.NestedJoin(#"Changed Type2", {"Account # 2"}, #"Chart of Accounts", {"Account #"}, "Chart of Accounts", JoinKind.LeftOuter),
    #"Expanded Chart of Accounts" = Table.ExpandTableColumn(#"Merged Queries", "Chart of Accounts", {"Multiply Rules"}, {"Multiply Rules"}),
    #"Added Custom" = Table.AddColumn(#"Expanded Chart of Accounts", "Multiplication", each [Amount] * [Multiply Rules]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"Multiplication", type number}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type1",{{"Multiplication", "Adjusted Value"}}),
    #"Removed Other Columns" = Table.SelectColumns(#"Renamed Columns2",{"Date", "Account", "Amount", "Account # 2", "Adjusted Value"}),
    #"Renamed Account #" = Table.RenameColumns(#"Removed Other Columns",{{"Account # 2", "Account #"}})
in
    #"Renamed Account #"